# Generated by Django 5.2.13 on 2026-04-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('hall', models.CharField(max_length=50)),
                ('booth', models.CharField(max_length=50)),
                ('sector', models.TextField()),
                ('logo_url', models.URLField()),
            ],
        ),
    ]
