# Generated by Django 6.0.2 on 2026-02-13 06:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('s3_path', models.CharField(max_length=1024)),
                ('is_active', models.BooleanField(default=False)),
                ('metrics', models.JSONField(default=dict)),
                ('parameters', models.JSONField(default=dict)),
            ],
            options={
                'unique_together': {('name', 'version')},
            },
        ),
    ]
